Questions:
  - key: type
    type: select
    label: "Select the type of change you're committing"
    data:
      options:
        - value: feat
          desc: "A new feature"
        - value: fix
          desc: "A bug fix"
        - value: docs
          desc: "Documentation only changes"
        - value: style
          desc: "Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)"
        - value: refactor
          desc: "A code change that neither fixes a bug nor adds a feature"
        - value: perf
          desc: "A code change that improves performance"
        - value: test
          desc: "Adding missing tests"
        - value: chore
          desc: "Changes to the build process or auxiliary tools and libraries such as documentation generation"
        - value: revert
          desc: "Revert to a commit"
        - value: WIP
          desc: "WIP: Work in progress"

  - key: scope
    type: text
    label: "What scope of this change? (e.g. backend or cli)"
    data:
      min: 1
      max: 66

  - key: subject
    type: text
    label: "Write a short, imperative tense description of change (max 66 chars)"
    data:
      min: 1
      max: 66

  - key: desc
    type: text
    data:
      min: 0
      max: 1000
    label: "Provide a large description of the changes: (press enter for skip)"

  - key: issuesConfirm
    type: select
    label: "Does this change affect any open issues"
    data:
      options:
        - value: no
        - value: yes
    subquestion_condition: yes
    subquestions:
      - key: issues
        type: text
        label: "Add issue reference (e.g. fix #123, re #123.)"
        data:
          min: 0
          max: 1000

TemplateCommit: |
  <type>(<scope>): <subject>

  <desc>

  <issues>
Colors:
  primary: "36"
  green: "32"
  red: "31"